# Generated by Django 4.1.5 on 2023-01-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_projectimage_profileimage_postimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimage", old_name="profile", new_name="post",
        ),
        migrations.RenameField(
            model_name="projectimage", old_name="profile", new_name="project",
        ),
    ]
