# Generated by Django 4.1.5 on 2023-01-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_comment_author_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to="portfolio.profile",
            ),
        ),
    ]
