# Generated by Django 4.1.5 on 2023-01-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("P", "Public"), ("H", "Hidden")], default="P", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("P", "Published"), ("D", "Draft")], default="P", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("P", "Public"), ("H", "Hidden")], default="P", max_length=1
            ),
        ),
    ]
