# Generated by Django 4.1.5 on 2023-01-29 17:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_comment_content_alter_postimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="content", field=ckeditor.fields.RichTextField(),
        ),
    ]
