# Generated by Django 4.1.5 on 2023-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="content", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post", name="content", field=models.TextField(),
        ),
    ]
