# Generated by Django 4.1.6 on 2023-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_alter_comment_content_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="postfile",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="postimage",
            name="alt",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
